services:
  order-db:
    image: postgres:16
    environment:
      POSTGRES_USER: lucas
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: orderdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-order-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:4.3.2-management
    container_name: orderflow-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: lucas
      RABBITMQ_DEFAULT_PASS: 1234

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: orderflow-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
volumes:
  postgres-order-data:

